default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: task-manager_development

test:
  <<: *default
  database: task-manager_test

production:
  <<: *default
  database: task-manager_production
  username: task-manager
  password: <%= ENV['TASK-MANAGER_DATABASE_PASSWORD'] %>
